apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment  # Deployment의 이름
  namespace: eof  # Deployment가 속할 네임스페이스
spec:
  replicas: 2  # 생성할 Pod의 복제본 수
  selector:
    matchLabels:
      app: nginx  # 선택할 라벨 지정 (이 라벨을 가진 Pod을 선택)
  template:
    metadata:
      labels:
        app: nginx  # Pod 템플릿에 지정할 라벨
    spec:
      containers:
        - name: nginx  # 컨테이너 이름
          image: shvic/projectf:dockerfile  # 사용할 컨테이너 이미지
          ports:
            - containerPort: 80  # 컨테이너가 수신할 포트 번호

---
apiVersion: v1  # API 버전 지정
kind: Service  # Service 리소스 종류 지정
metadata:
  name: nginx-service  # Service 이름 지정
  namespace: eof  # 네임스페이스 지정
spec:
  type: LoadBalancer  # Service 타입 지정 (LoadBalancer로 외부에 노출)
  selector:
    app: nginx  # 선택할 라벨 지정 (이 라벨을 가진 Pod을 선택)
  ports:
    - protocol: TCP  # 사용할 프로토콜
      port: 80  # Service가 노출할 포트 (클러스터 외부에서 접근할 포트)
      targetPort: 8000  # Pod에서 노출할 포트 (컨테이너 내부 포트)

---
apiVersion: v1  # API 버전 지정
kind: Service  # Service 리소스 종류 지정
metadata:
  name: aws-load-balancer-webhook-service  # Service 이름 지정
  namespace: kube-system  # 네임스페이스 지정
spec:
  type: NodePort  # Service 타입 지정 (NodePort로 외부에 노출)
  ports:
    - port: 443  # Service가 노출할 포트 (클러스터 외부에서 접근할 포트)
      targetPort: 9443  # Pod에서 노출할 포트 (컨테이너 내부 포트)
      nodePort: 30000  # 노드 포트 지정 (필요에 따라 원하는 포트 번호로 대체)
  selector:
    app.kubernetes.io/name: aws-load-balancer-controller  # 선택할 라벨 지정 (이 라벨을 가진 Pod을 선택)

---
apiVersion: networking.k8s.io/v1  # Ingress 리소스의 API 버전
kind: Ingress  # 생성할 리소스 종류는 Ingress
metadata:
  name: ingress  # Ingress 리소스의 이름
  namespace: eof  # Ingress 리소스가 속할 네임스페이스
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing  # ALB를 인터넷에 노출시키기 위한 설정
    alb.ingress.kubernetes.io/target-type: ip  # 대상 유형을 IP로 설정 (IP 주소를 사용하여 트래픽을 분배)
    alb.ingress.kubernetes.io/load-balancer-name: app-loadbalancer  # 로드 밸런서 이름
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'  # ALB가 수신할 포트 설정
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-1:058264352854:certificate/beb8d205-f19f-40e8-b424-c672c951e940  # SSL 인증서 ARN
spec:
  ingressClassName: alb  # 사용할 Ingress 클래스 이름 (ALB 사용)
  rules:
    - host: www.cloudeof.com  # 이 호스트명으로 들어오는 트래픽에 대한 규칙 정의
      http:
        paths:
          - path: /*  # 모든 경로에 대한 트래픽 처리
            pathType: Prefix  # 경로 타입 (Prefix 매칭)
            backend:
              service:
                name: nginx-service  # 백엔드 서비스 이름
                port:
                  number: 80  # 백엔드 서비스가 수신할 포트 번호
